# Generated by Django 4.0.3 on 2022-04-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_following_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='theme_choice',
            field=models.CharField(choices=[('dm', 'main'), ('lm', 'light')], default='main', max_length=100),
        ),
    ]
